version: '3'

vars:
  APP_NAME: "paint-match-ai"
  BIN_DIR: "dist"
  PACKAGE_MANAGER: '{{.PACKAGE_MANAGER | default "npm"}}'
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9245}}'

includes:
  common: ./build/Taskfile.yml
  darwin: ./build/darwin/Taskfile.yml

tasks:
  build:
    summary: Builds the application
    cmds:
      - task: "{{OS}}:build"

  run:
    summary: Runs the application
    cmds:
      - task: "{{OS}}:run"

  dev:
    summary: Runs the application in development mode
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}

  seed:
    summary: Runs the seed command to populate database
    cmds:
      - go run ../api/cmd/seed {{.CLI_ARGS}}
