// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {ai} from '../models';

export function Close():Promise<void>;

export function CompareColors(arg1:Array<number>):Promise<Array<main.SearchResultDTO>>;

export function FindEquivalences(arg1:number):Promise<Array<main.SearchResultDTO>>;

export function FindSimilar(arg1:number,arg2:number,arg3:number,arg4:number,arg5:number):Promise<Array<main.SearchResultDTO>>;

export function GetAllPaints():Promise<Array<main.PaintDTO>>;

export function GetManufacturers():Promise<Array<main.ManufacturerDTO>>;

export function GetPaintByID(arg1:number):Promise<main.PaintDTO>;

export function GetStats():Promise<main.StatsDTO>;

export function ProcessQuery(arg1:string):Promise<ai.Response>;

export function SearchPaints(arg1:string):Promise<Array<main.PaintDTO>>;

export function SuggestRecipe(arg1:number,arg2:number,arg3:number,arg4:number):Promise<main.RecipeDTO>;
