// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['PaintService']['Close']();
}

export function CompareColors(arg1) {
  return window['go']['main']['PaintService']['CompareColors'](arg1);
}

export function FindEquivalences(arg1) {
  return window['go']['main']['PaintService']['FindEquivalences'](arg1);
}

export function FindSimilar(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['PaintService']['FindSimilar'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAllPaints() {
  return window['go']['main']['PaintService']['GetAllPaints']();
}

export function GetManufacturers() {
  return window['go']['main']['PaintService']['GetManufacturers']();
}

export function GetPaintByID(arg1) {
  return window['go']['main']['PaintService']['GetPaintByID'](arg1);
}

export function GetStats() {
  return window['go']['main']['PaintService']['GetStats']();
}

export function ProcessQuery(arg1) {
  return window['go']['main']['PaintService']['ProcessQuery'](arg1);
}

export function SearchPaints(arg1) {
  return window['go']['main']['PaintService']['SearchPaints'](arg1);
}

export function SuggestRecipe(arg1, arg2, arg3, arg4) {
  return window['go']['main']['PaintService']['SuggestRecipe'](arg1, arg2, arg3, arg4);
}
